service: aws-node-rest-api-mongodb

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1


functions:
  
  imageResize:
    handler: handler.imageResize
    events:
      - http:
          path: imageResize/{width}/{key}
          method: get
          cors: true          
        
